env: "dev"

server:
  host: "0.0.0.0"
  port: "5000"
  timeout: 7s
  idle_timeout: 30s

database:
  database: "bookings_db"
  host: "db"
  port: "5433"
  user: "postgres"
  password: "bookings_pass"
  ssl: "disable"
  max_opened_connections: 10

jwt:
  secret: "verysecretivejwt"
  expiration: 2160h

tracer:
  endpoint_url: "http://otelcol:4318"
  sampling_rate: 1.0