FROM maven:3.8-jdk-11 as maven_build

COPY . /github.com/nikitads9/godassinn/search/

WORKDIR /github.com/nikitads9/godassinn/search/

RUN mvn clean package

FROM openjdk:23-slim-bullseye

WORKDIR /root/

COPY --from=maven_build /github.com/nikitads9/godassinn/search/target/*.jar ./app.jar

ENTRYPOINT ["java","-jar","app.jar"]